version: 2

builds:
  - id: tatara
    main: ./cmd/tatara
    binary: tatara
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin]
    goarch: [amd64]
    ldflags:
      - -s -w
      - -X github.com/szymonrychu/tatara-cli/internal/version.Version={{ .Version }}
      - -X github.com/szymonrychu/tatara-cli/internal/version.Commit={{ .ShortCommit }}
      - -X github.com/szymonrychu/tatara-cli/internal/version.Date={{ .Date }}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-snapshot"
